export enum API {
  BASE_URL = "https://api.open5e.com/v1",
  SPELLS = "/spells",
  SPELLLIST = "/spelllist",
  MONSTERS = "/monsters",
  DOCUMENTS = "/documents",
  BACKGROUNDS = "/backgrounds",
  PLANES = "/planes",
  SECTIONS = "/sections",
  FEATS = "/feats",
  CONDITIONS = "/conditions",
  RACES = "/races",
  CLASSES = "/classes",
  MAGICITEMS = "/magicitems",
  WEAPONS = "/weapons",
  ARMOR = "/armor",
  SEARCH = "/search",
}
